### ISSUE TITLE
[web-app-draw-io] App don't work with 8.0.1

### ISSUE THREAD

**Issue by FrankM64** [opencloud-eu/web-extensions#563]
### Initial Checklist

- [x] I understand this is a bug report and questions should be posted in the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
- [x] I searched [issues](https://github.com/opencloud-eu/web-extensions/issues?q=is%3Aissue) and couldn’t find anything (or linked relevant results below)

### Bug Description

I have installed web-app-draw-io. Before 8.0.0 ist works. With 8.0.1 App don't work anymore.

<img width="651" height="229" alt="Image" src="https://github.com/user-attachments/assets/346458c2-09e5-4068-ae7b-0250f02b7ff3" />

I see this error "RuntimeError: cannot create application, undefined is not a function"

### Reproduction Steps

1. Add web-app-draw-io to your opencloud instance
2. open an .drawio image
3. finally, read the error window ;)

### Expected Outcome

open  .drawio image

### Actual Outcome

"RuntimeError: cannot create application, undefined is not a function"

**Comment by JammingBen** [comment]
I can't imagine that something broke between `8.0.0` and `8.0.1` here 🤔 Are you running the latest version `2.2.0` of the app? https://github.com/opencloud-eu/web-extensions/releases/tag/draw-io-v2.2.0

**Comment by FrankM64** [comment]
I have checked the version, and my version wasn't 2.2.0. Now i have installed the actual 2.2.0 version.
Thank you and sorry, i will close this issue.
